name: lint and test
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read
  packages: read

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const currentLabels = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            if (currentLabels.data.some(({ name }) => name === 'tests failed')) {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'tests failed'
              })
            }

            if (currentLabels.data.some(({ name }) => name === 'tests passed')) {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'tests passed'
              })
            }

  test-suite:
    runs-on: ubuntu-latest
    needs: remove-labels
    if: ${{ always() }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          base=${{ github.base_ref }}
          echo "BRANCH=${base^^}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn install

      - name: lint
        id: lint
        run: yarn lint

      - name: test
        if: steps.lint.outcome == 'success'
        id: test
        run: yarn test:coverage

      - name: code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          output: both

      - name: add coverage to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          path: code-coverage-results.md

  add-label:
    runs-on: ubuntu-latest
    needs: test-suite
    if: ${{ always() }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const prevStepFailed = ${{ contains(join(needs.*.result, ','), 'failure') }}
            if (prevStepFailed) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['tests failed']
              })
            } else {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['tests passed']
              })
            }

