name: lint and test

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: read
  packages: read

jobs:
  remove-labels:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const currentLabels = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            if (currentLabels.data.some(({ name }) => name === 'tests failed')) {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'tests failed'
              })
            }

            if (currentLabels.data.some(({ name }) => name === 'tests passed')) {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'tests passed'
              })
            }

  test-suite:
    runs-on: ubuntu-latest
    needs: [remove-labels]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps

      - name: ci
        env:
          BLOB_READ_WRITE_TOKEN: vercel_blob_rw_xxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          BLOB_STORE_ID: "xxxxxxxxxxxxxxxx"
        id: ci
        run: pnpm cicd

      - name: code coverage report
        if: steps.ci.outcome == 'success'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          output: both

      - name: add coverage to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          path: code-coverage-results.md

  add-label:
    runs-on: ubuntu-latest
    needs: test-suite
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const prevStepFailed = ${{ contains(join(needs.*.result, ','), 'failure') }}
            if (prevStepFailed) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['tests failed']
              })
            } else {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['tests passed']
              })
            }
