# for PR deploys
name: Generate PR Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
  NEON_BASE_URL: ${{ secrets.NEON_BASE_URL }}
on:
  pull_request:
    types: [opened, synchronize]
  workflow_run:
    workflows:
      - "lint and test"
    types:
      - "completed"

jobs:
  create-sync-database:
    runs-on: ubuntu-latest

    if: |
      (startsWith(github.head_ref, 'chore/') ||
      startsWith(github.head_ref, 'docs/') ||
      startsWith(github.head_ref, 'feat/') ||
      startsWith(github.head_ref, 'fix/') ||
      startsWith(github.head_ref, 'perf/') ||
      startsWith(github.head_ref, 'refactor/') ||
      startsWith(github.head_ref, 'revert/') ||
      startsWith(github.head_ref, 'style/') ||
      startsWith(github.head_ref, 'test/'))
    steps:
      - uses: actions/checkout@v4
        if: github.event.action == 'opened'
      - name: Setup PostgreSQL
        if: github.event.action == 'opened'
        uses: tj-actions/install-postgresql@v3
        with:
          postgresql-version: 15
      - name: Determine Base DB
        if: github.event.action == 'opened'
        id: set-base-db
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          if [[ $BASE_BRANCH == develop ]]
          then
            BASE_DB_URL=${{ secrets.MAIN_DB_URL }} || ""
          elif [[ $BASE_BRANCH == preprod ]]
          then
            BASE_DB_URL=${{ secrets.MAIN_DB_URL }} || ""
          elif [[ $BASE_BRANCH == main ]]
          then
            BASE_DB_URL=${{ secrets.MAIN_DB_URL }}
          else
            BASE_URL="${BASE_BRANCH/\//%2F}"
            echo "BASE_URL: ${BASE_URL}"
            BASE_DB_URL="${{ secrets.NEON_BASE_URL }}/${BASE_URL}"
          fi

          echo "BASE_DB_URL=${BASE_DB_URL}" >> "$GITHUB_ENV"
      - name: Create DB
        if: github.event.action == 'opened'
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          CURRENT_URL="${BRANCH_NAME/\//%2F}"
          CURRENT_DB_URL="${{ secrets.NEON_BASE_URL }}/${CURRENT_URL}"

          echo "CURRENT_DB_URL=${CURRENT_DB_URL}" >> "$GITHUB_ENV"
          npx neonctl databases create --project-id='${{ secrets.NEON_PROJECT_ID }}' --branch=main --name=${BRANCH_NAME} --api-key='${{ secrets.NEON_API_KEY }}'
      - name: Copy DB
        if: github.event.action == 'opened'
        run: |
          pg_dump -Fc -v -d ${{ env.BASE_DB_URL }} | pg_restore -v -x --no-owner -d "${{ env.CURRENT_DB_URL }}?sslmode=require"

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: create-sync-database
    if: |
      (startsWith(github.head_ref, 'chore/') ||
      startsWith(github.head_ref, 'docs/') ||
      startsWith(github.head_ref, 'feat/') ||
      startsWith(github.head_ref, 'fix/') ||
      startsWith(github.head_ref, 'perf/') ||
      startsWith(github.head_ref, 'refactor/') ||
      startsWith(github.head_ref, 'revert/') ||
      startsWith(github.head_ref, 'style/') ||
      startsWith(github.head_ref, 'test/'))
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18.0.0

      - name: Get DB URL
        run: |
          CURRENT_BRANCH=${{ github.event.pull_request.head.ref }}
          CURRENT_DB_URL="${{ secrets.NEON_BASE_URL }}/${CURRENT_BRANCH}"

          echo "CURRENT_DB_URL=$CURRENT_DB_URL" >> "$GITHUB_ENV"
      - name: Deploy
        id: deploy
        run: |
          npx vercel --token=${{ secrets.VERCEL_TOKEN }} deploy --build-env POSTGRES_URL=${{ env.CURRENT_DB_URL }} --build-env IS_PREVIEW=true --env POSTGRES_URL=${{ env.CURRENT_DB_URL }} --env IS_PREVIEW=true > deployment-url.txt
          echo "deploymentUrl=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
      - name: Add URL to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.issue.number }}
          header: pr-metadata
          message: |
            | Name | URL |
            | ---- | --- |
            | Preview | ${{ env.deployment-url }} |
            | Admin | ${{ env.deployment-url }}/admin |
